### PR TITLE
fixed : quic_sort -> quick_sort 함수명 수정

### PR DESCRIPTION
**Pull request by Geunbaek**
### Pull-request Type (fix, feat, bug, doc, chore, test, etc...) 

- fix

### Current Behavior (Link to an open issue)

- quic_sort 함수 명 오타
-

### New Behavior (if this is a feature change)

- quick_sort 함수 명 수정
-

### Other information

-
-

### CODE REVIEW

**Review by wyuinche — APPROVED** [review]
LGTM!

**Comment by hjoo3355** [comment]
NACK

**Review by uom6uoc — APPROVED** [review]
LGTM!

**Review by soonkuk — APPROVED** [review]
👍

**Comment by hjoo3355** [comment]
LGTM!

**Review by hjoo3355 — APPROVED** [review]

**Review by congchu — APPROVED** [review]
Very Good👍

**Pull request merged**
